version: "3.8"

services:
  chatgpt-discord:
    build: .
    container_name: chatgpt-discord-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
